<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_HomeAbsoluteSwitch" Id="{4b3b9350-559a-4825-85f8-75f4fbbac869}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HomeAbsoluteSwitch
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HomeAbsoluteSwitch">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>