<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Axis_1" Id="{734d3f4c-c951-47c9-b623-1f718ea980b1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Axis_1
VAR
    bLimitPowerAxis1 AT %Q*: BOOL := TRUE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Initial parameters of an Axis
IF _TaskInfo[fbGetCurTaskIndex.index].FirstCycle THEN
    //Initial default values:
    GVL.astAxes[1].stConfig.eHomeSeq := 0;
    GVL.astAxes[1].stConfig.fHomePosition := 0.0;
    GVL.astAxes[1].stConfig.fHomeFinishDistance := -1;
END_IF

ACT_1_Interlock();

// Brake control from GUI
main.stHWStatusX.bBrakeReleased:=main.stHWControlX.bBrakeReleaseCmd;

// Enable Cmd from GUI
GVL.astAxes[1].stControl.bEnable:=main.stHWControlX.bEnable;
main.stHWStatusX.bEnabled:=GVL.astAxes[1].stStatus.bEnabled;

// Trigger Abs movement from GUI
IF main.stHWControlX.bExecuteAbsPos  AND NOT GVL.astAxes[1].stStatus.bBusy THEN
  GVL.astAxes[1].stControl.eCommand:=E_MotionFunctions.eMoveAbsolute;
  GVL.astAxes[1].stControl.bExecute:=TRUE;
  main.stHWControlX.bExecuteAbsPos:=FALSE;
END_IF

// Trigger Home vs LimitFwd (should be valid for all axes) from GUI
IF main.stHWControlX.bExecuteHome  AND NOT GVL.astAxes[1].stStatus.bBusy THEN
  GVL.astAxes[1].stControl.eCommand:=E_MotionFunctions.eHome;
  GVL.astAxes[1].stConfig.eHomeSeq:=E_HomingRoutines.eHomeToLimit_Fwd;
  GVL.astAxes[1].stControl.bExecute:=TRUE;
  main.stHWControlX.bExecuteHome:=FALSE;
END_IF

//Stop Motion from GUI
IF main.stHWControlX.bExecuteStop THEN
  GVL.astAxes[1].stControl.bStop := NOT(GVL.astAxes[1].stControl.bStop);
  GVL.astAxes[1].stControl.bExecute:=FALSE;
  main.stHWControlX.bExecuteStop:=FALSE;
END_IF

// Error Code
GVL.astAxes[1].stStatus.nErrorID;

main.stHWStatusX.bBusy:=GVL.astAxes[1].stStatus.bBusy;
GVL.astAxes[1].stControl.bReset:=main.stHWControlX.bExecuteReset;
main.stHWControlX.bExecuteReset:=FALSE;
main.stHWStatusX.bHomed:=GVL.astAxes[1].stStatus.bHomed;
main.stHWStatusX.bHomingCmdActive:=GVL.astAxes[1].stControl.eCommand=E_MotionFunctions.eHome AND 
                                   GVL.astAxes[1].stConfig.eHomeSeq=E_HomingRoutines.eHomeToLimit_Fwd;

// Hard code velocities and acc/dec
GVL.astAxes[1].stControl.fAcceleration:=GVL_Parameters.fStepperTargetAcc;
GVL.astAxes[1].stControl.fDeceleration:=GVL_Parameters.fStepperTargetAcc;
GVL.astAxes[1].stControl.fVelocity:=GVL_Parameters.fStepperTargetVelo;

// Check position is inside limits (and homed)
main.stHWStatusX.bLoLoAlm:=gvl.astAxes[1].stStatus.fActPosition < GVL_Parameters.fXRangeL2 OR NOT main.stHWStatusX.bHomed;
main.stHWStatusX.bLoAlm:=gvl.astAxes[1].stStatus.fActPosition < GVL_Parameters.fXRangeL1 OR NOT main.stHWStatusX.bHomed;
main.stHWStatusX.bHiAlm:=gvl.astAxes[1].stStatus.fActPosition > GVL_Parameters.fXRangeH1 OR NOT main.stHWStatusX.bHomed;
main.stHWStatusX.bhiHiAlm:=gvl.astAxes[1].stStatus.fActPosition > GVL_Parameters.fXRangeH2 OR NOT main.stHWStatusX.bHomed;
]]></ST>
    </Implementation>
    <Action Name="ACT_1_Interlock" Id="{ca43ea7f-b212-458e-a066-b237d81a70c7}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWStatusX.bHwStatusOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">145L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">139L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s20_IPOS8020.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">136L</v>
                              </o>
                              <v n="Id">135L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s10_EL7201.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">138L</v>
                              </o>
                              <v n="Id">137L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s15_EL6695.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">142L</v>
                              </o>
                              <v n="Id">141L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s13_EL3214.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">144L</v>
                              </o>
                              <v n="Id">143L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWStatusDev.bFC11_Fuse24VOK"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">162L</v>
                              </o>
                              <v n="Id">161L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWStatusDev.bTA01_TA02_24VSupplyOK"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">164L</v>
                              </o>
                              <v n="Id">163L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">140L</v>
                        </o>
                        <v n="Id">146L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">131L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[1].stControl.bInterlock"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">64L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems">
                            <o t="BoxTreeAssign">
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" cet="Operand">
                                  <o>
                                    <v n="Operand">"main.stHWStatusX.bGeneralILOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">true</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">165L</v>
                                  </o>
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <o n="RValue" t="BoxTreeBox">
                                <v n="BoxType">"&amp;"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">66L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems">
                                    <n />
                                  </l2>
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <l2 n="InputFlags" cet="Flags">
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <o>
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                </l2>
                                <l2 n="InputItems">
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Main.stHWStatusDev.bEStopOK"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">5L</v>
                                    </o>
                                    <v n="Id">4L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWStatusX.bBrakeReleased"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">11L</v>
                                    </o>
                                    <v n="Id">10L</v>
                                  </o>
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"&gt;"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">72L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems">
                                        <n />
                                      </l2>
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems" cet="BoxTreeOperand">
                                      <o>
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"main.stHWStatusX.fStepperTemp"</v>
                                          <v n="Type">"LREAL"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">15L</v>
                                        </o>
                                        <v n="Id">14L</v>
                                      </o>
                                      <o>
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"5"</v>
                                          <v n="Type">"INT"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">19L</v>
                                        </o>
                                        <v n="Id">18L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v></v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                      </l2>
                                    </o>
                                    <v n="CallType" t="Operator">Greater</v>
                                    <v n="EN">false</v>
                                    <v n="ENO">false</v>
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">73L</v>
                                  </o>
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"&lt;"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">74L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems">
                                        <n />
                                      </l2>
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems" cet="BoxTreeOperand">
                                      <o>
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"main.stHWStatusX.fStepperTemp"</v>
                                          <v n="Type">"LREAL"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">47L</v>
                                        </o>
                                        <v n="Id">46L</v>
                                      </o>
                                      <o>
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"GVL_Parameters.fStepperTempH2"</v>
                                          <v n="Type">"LREAL"</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">49L</v>
                                        </o>
                                        <v n="Id">48L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v></v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                      </l2>
                                    </o>
                                    <v n="CallType" t="Operator">Less</v>
                                    <v n="EN">false</v>
                                    <v n="ENO">false</v>
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">75L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stStatus.bAxisStandStillStatus"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">59L</v>
                                    </o>
                                    <v n="Id">58L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWStatusX.bLimitMaxMax"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">78L</v>
                                    </o>
                                    <v n="Id">77L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWStatusX.bLimitMinMin"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">80L</v>
                                    </o>
                                    <v n="Id">79L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWStatusDev.bBeamOff"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">82L</v>
                                    </o>
                                    <v n="Id">81L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWControlX.bAllowMotionGUI"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">108L</v>
                                    </o>
                                    <v n="Id">107L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"main.stHWStatusX.bHwStatusOK"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">122L</v>
                                    </o>
                                    <v n="Id">121L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v></v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                  </l2>
                                </o>
                                <v n="CallType" t="Operator">Ampersand</v>
                                <v n="EN">false</v>
                                <v n="ENO">false</v>
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">67L</v>
                              </o>
                              <v n="Id">166L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWControlX.bManualInterlockOverride"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">63L</v>
                              </o>
                              <v n="Id">62L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">65L</v>
                        </o>
                        <v n="Id">13L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[1].stInputs.bLimitBwd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">105L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"main.stHWStatusX.bLimitMin"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">104L</v>
                          </o>
                          <v n="Id">103L</v>
                        </o>
                        <v n="Id">106L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">102L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[1].stInputs.bLimitFwd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">96L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"main.stHWStatusX.bLimitMax"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">87L</v>
                          </o>
                          <v n="Id">86L</v>
                        </o>
                        <v n="Id">97L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">83L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWStatusX.bGeneralAndOverrideILOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">1</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">113L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"gvl.astAxes[1].stControl.bInterlock"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">112L</v>
                          </o>
                          <v n="Id">111L</v>
                        </o>
                        <v n="Id">114L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">110L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWstatusX.bManualInterlockOverride"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">119L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"main.stHWControlX.bManualInterlockOverride"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">118L</v>
                          </o>
                          <v n="Id">117L</v>
                        </o>
                        <v n="Id">120L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">116L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWstatusX.bSumBwdILOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">190L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">184L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"gvl.astAxes[1].stStatus.bBwEnabled"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">187L</v>
                              </o>
                              <v n="Id">186L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"gvl.astAxes[1].stControl.bInterlock"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">189L</v>
                              </o>
                              <v n="Id">188L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">185L</v>
                        </o>
                        <v n="Id">191L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">183L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWstatusX.bSumFwdILOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">181L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">179L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"gvl.astAxes[1].stStatus.bFwEnabled"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">176L</v>
                              </o>
                              <v n="Id">175L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"gvl.astAxes[1].stControl.bInterlock"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">178L</v>
                              </o>
                              <v n="Id">177L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">180L</v>
                        </o>
                        <v n="Id">182L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">172L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="Axis_1">
      <LineId Id="46" Count="6" />
      <LineId Id="56" Count="1" />
      <LineId Id="66" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="108" Count="1" />
      <LineId Id="87" Count="0" />
      <LineId Id="116" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="81" Count="0" />
      <LineId Id="77" Count="1" />
      <LineId Id="41" Count="0" />
      <LineId Id="83" Count="0" />
      <LineId Id="85" Count="0" />
      <LineId Id="95" Count="0" />
      <LineId Id="97" Count="1" />
      <LineId Id="102" Count="1" />
      <LineId Id="99" Count="0" />
      <LineId Id="101" Count="0" />
      <LineId Id="96" Count="0" />
      <LineId Id="131" Count="0" />
      <LineId Id="88" Count="0" />
      <LineId Id="90" Count="1" />
      <LineId Id="157" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="117" Count="2" />
      <LineId Id="94" Count="0" />
      <LineId Id="115" Count="0" />
      <LineId Id="114" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="121" Count="0" />
      <LineId Id="120" Count="0" />
      <LineId Id="142" Count="1" />
      <LineId Id="156" Count="0" />
      <LineId Id="144" Count="0" />
      <LineId Id="123" Count="0" />
      <LineId Id="145" Count="1" />
      <LineId Id="155" Count="0" />
      <LineId Id="148" Count="0" />
      <LineId Id="147" Count="0" />
      <LineId Id="149" Count="0" />
      <LineId Id="152" Count="0" />
      <LineId Id="151" Count="0" />
      <LineId Id="154" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>