<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Axis_3" Id="{1bec8e22-b127-4216-8a57-916e22c1b930}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Axis_3
VAR
	bLimitPowerAxis3 AT %Q*: BOOL := TRUE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Initial parameters of an Axis
IF _TaskInfo[fbGetCurTaskIndex.index].FirstCycle THEN
    //Initial default values:
    GVL.astAxes[3].stConfig.eHomeSeq := 1;
    GVL.astAxes[3].stConfig.fHomePosition := 0.0;
    GVL.astAxes[3].stConfig.fHomeFinishDistance := -1;
END_IF

ACT_3_Interlock();

main.stHWStatusZ.bBrakeReleased:=FALSE;  // Not used
main.stHWControlZ.bBrakeReleaseCmd:=FALSE; // Not used

// Enable Cmd from GUI
GVL.astAxes[3].stControl.bEnable:=main.stHWControlZ.bEnable;
main.stHWStatusZ.bEnabled:=GVL.astAxes[3].stStatus.bEnabled;

// Trigger Abs movement from GUI
IF main.stHWControlZ.bExecuteAbsPos  AND NOT GVL.astAxes[3].stStatus.bBusy THEN
  GVL.astAxes[3].stControl.eCommand:=E_MotionFunctions.eMoveAbsolute;
  GVL.astAxes[3].stControl.bExecute:=TRUE;
  main.stHWControlZ.bExecuteAbsPos:=FALSE;
END_IF

// Trigger Home vs LimitFwd (should be valid for all axes) from GUI
IF main.stHWControlZ.bExecuteHome  AND NOT GVL.astAxes[3].stStatus.bBusy THEN
  GVL.astAxes[3].stControl.eCommand:=E_MotionFunctions.eHome;
  GVL.astAxes[3].stConfig.eHomeSeq:=E_HomingRoutines.eHomeToLimit_Fwd;
  GVL.astAxes[3].stControl.bExecute:=TRUE;
  main.stHWControlZ.bExecuteHome:=FALSE;
END_IF

//Stop Motion from GUI
IF main.stHWControlZ.bExecuteStop THEN
  GVL.astAxes[3].stControl.bStop := NOT(GVL.astAxes[3].stControl.bStop);
  main.stHWControlZ.bExecuteStop:=FALSE;
END_IF

main.stHWStatusZ.bBusy:=GVL.astAxes[3].stStatus.bBusy;
GVL.astAxes[3].stControl.bReset:=main.stHWControlZ.bExecuteReset;
main.stHWControlZ.bExecuteReset:=FALSE;
]]></ST>
    </Implementation>
    <Action Name="ACT_3_Interlock" Id="{9a8d4546-6892-40d1-9370-4b045bf9101e}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWStatusZ.bHwStatusOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">217L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">207L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s22_IPOS8020.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">210L</v>
                              </o>
                              <v n="Id">209L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s12_EL7201.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">212L</v>
                              </o>
                              <v n="Id">211L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s15_EL6695.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">214L</v>
                              </o>
                              <v n="Id">213L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.fb_s13_EL3214.bError"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">216L</v>
                              </o>
                              <v n="Id">215L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">208L</v>
                        </o>
                        <v n="Id">218L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">206L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWStatusZ.bParkingRangeEnabled"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">113L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"OR"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">115L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems">
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"GVL_Parameters.bTargetRotorInstalled"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">106L</v>
                              </o>
                              <v n="Id">105L</v>
                            </o>
                            <o t="BoxTreeBox">
                              <v n="BoxType">"&amp;"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">121L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stStatus.bAxisStandStillStatus"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">108L</v>
                                  </o>
                                  <v n="Id">107L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&lt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">139L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"gvl.astAxes[1].stStatus.fActPosition"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">126L</v>
                                      </o>
                                      <v n="Id">125L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"GVL_Parameters.fXRangeH1"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">128L</v>
                                      </o>
                                      <v n="Id">127L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Less</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">140L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&gt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">141L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"gvl.astAxes[1].stStatus.fActPosition"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">134L</v>
                                      </o>
                                      <v n="Id">133L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"GVL_Parameters.fXRangeL1"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">136L</v>
                                      </o>
                                      <v n="Id">135L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Greater</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">142L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"gvl.astAxes[1].stStatus.bHomed"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">144L</v>
                                  </o>
                                  <v n="Id">143L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"gvl.astAxes[2].stStatus.bHomed"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">146L</v>
                                  </o>
                                  <v n="Id">145L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"gvl.astAxes[3].stStatus.bHomed"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">148L</v>
                                  </o>
                                  <v n="Id">147L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&lt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">163L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"gvl.astAxes[2].stStatus.fActPosition"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">166L</v>
                                      </o>
                                      <v n="Id">165L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"GVL_Parameters.fYRangeH1"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">168L</v>
                                      </o>
                                      <v n="Id">167L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Less</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">164L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&gt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">169L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"gvl.astAxes[2].stStatus.fActPosition"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">172L</v>
                                      </o>
                                      <v n="Id">171L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"GVL_Parameters.fYRangeL1"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">174L</v>
                                      </o>
                                      <v n="Id">173L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Greater</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">170L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v></v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Ampersand</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">122L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Or</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">116L</v>
                        </o>
                        <v n="Id">114L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">76L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[3].stControl.bInterlock"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"&amp;"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">64L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems">
                            <o t="BoxTreeBox">
                              <v n="BoxType">"&amp;"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">66L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <l2 n="InputFlags" cet="Flags">
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                              </l2>
                              <l2 n="InputItems">
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"Main.stHWStatusDev.bEStopOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">5L</v>
                                  </o>
                                  <v n="Id">4L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWStatusDev.bFC11_Fuse24VOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">7L</v>
                                  </o>
                                  <v n="Id">6L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWStatusDev.bTA01_TA02_24VSupplyOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">9L</v>
                                  </o>
                                  <v n="Id">8L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&gt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">72L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"main.stHWStatusZ.fStepperTemp"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">15L</v>
                                      </o>
                                      <v n="Id">14L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"5"</v>
                                        <v n="Type">"INT"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">19L</v>
                                      </o>
                                      <v n="Id">18L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Greater</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">73L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"&lt;"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">74L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"main.stHWStatusZ.fStepperTemp"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">47L</v>
                                      </o>
                                      <v n="Id">46L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"GVL_Parameters.fStepperTempH2"</v>
                                        <v n="Type">"LREAL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">49L</v>
                                      </o>
                                      <v n="Id">48L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Less</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">75L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stStatus.bAxisStandStillStatus"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">59L</v>
                                  </o>
                                  <v n="Id">58L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWStatusZ.bLimitMaxMax"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">78L</v>
                                  </o>
                                  <v n="Id">77L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"SEL"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">89L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"main.stHWStatusZ.bParkingRangeEnabled"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">82L</v>
                                      </o>
                                      <v n="Id">81L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"main.stHWStatusZ.bLimitMinMin"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">86L</v>
                                      </o>
                                      <v n="Id">85L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"main.stHWStatusZ.bLimitMinMinPark"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">92L</v>
                                      </o>
                                      <v n="Id">91L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>INT</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Sel</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">90L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWStatusDev.bBeamOff"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">102L</v>
                                  </o>
                                  <v n="Id">101L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWControlZ.bAllowMotionGUI"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">194L</v>
                                  </o>
                                  <v n="Id">193L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"main.stHWStatusZ.bHwStatusOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">220L</v>
                                  </o>
                                  <v n="Id">219L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v></v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Ampersand</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">67L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWControlZ.bManualInterlockOverride"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">63L</v>
                              </o>
                              <v n="Id">62L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Ampersand</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">65L</v>
                        </o>
                        <v n="Id">13L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[3].stInputs.bLimitBwd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">191L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"SEL"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">187L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWStatusZ.bParkingRangeEnabled"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">184L</v>
                              </o>
                              <v n="Id">183L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWStatusZ.bLimitMin"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">186L</v>
                              </o>
                              <v n="Id">185L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"main.stHWStatusZ.bLimitMinPark"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">190L</v>
                              </o>
                              <v n="Id">189L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>INT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Sel</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">188L</v>
                        </o>
                        <v n="Id">192L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">180L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"gvl.astAxes[3].stInputs.bLimitFwd"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">178L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"main.stHWStatusZ.bLimitMax"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">177L</v>
                          </o>
                          <v n="Id">176L</v>
                        </o>
                        <v n="Id">179L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">175L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWStatusZ.bSumILOK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">1</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">198L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"gvl.astAxes[3].stControl.bInterlock"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">197L</v>
                          </o>
                          <v n="Id">196L</v>
                        </o>
                        <v n="Id">199L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">195L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"main.stHWstatusZ.bManualInterlockOverride"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">203L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"main.stHWControlZ.bManualInterlockOverride"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">202L</v>
                          </o>
                          <v n="Id">201L</v>
                        </o>
                        <v n="Id">204L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">200L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="Axis_3">
      <LineId Id="20" Count="0" />
      <LineId Id="29" Count="5" />
      <LineId Id="60" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="92" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="94" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="72" Count="19" />
      <LineId Id="96" Count="0" />
      <LineId Id="95" Count="0" />
      <LineId Id="97" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="98" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>